name: ci-test
on: [push, pull_request]
jobs:
  ci-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/alessandrobiaggi/ci-test:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
    steps:
      - run: |
          echo "Hello, container!"
        name: container greeting


