name: ci-test
on: [push, pull_request]
jobs:
  ci-test:
    runs-on: ubuntu-latest
    container: ghcr.io/alessandrobiaggi/ci-test:latest
    steps:
      - run: |
          echo "Hello, container!"
        name: container greeting


